server:
  port: 8081

# 配置前缀和后缀
spring:
  mvc:
    view:
      prefix: /jsp
      suffix: .jsp
  # 注册数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/login
    username: test
    password: test@com


mybatis:
  # 注册映射文件
  mapper-locations: classpath:com/rom/dao/LoginMapper.xml
  # 注册实体类别名
  type-aliases-package: com.rom.pojo.domain

